dist: xenial
language: go
go:
- 1.11.x

# before_install
# install - install any dependencies required
install:
    - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.58.1/hugo_extended_0.58.1_Linux-64bit.deb
    - sudo dpkg -i /tmp/hugo.deb

before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo --minify

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  local-dir: public
  on:
    branch: master  